# tasks file
---
- name: change owner (and group)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('www-data') }}"
    group: "{{ item.group | default(item.owner) | default('www-data') }}"
    recurse: true
  with_items: "{{ wordpress_installs }}"
