---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../defaults/main.yml"
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
    - name: include tasks
      include: "{{ playbook_dir }}/../../tests/tasks/pre.yml"
  handlers:
    - import_tasks: "{{ playbook_dir }}/../../tests/handlers/main.yml"
