---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../defaults/main.yml"
    - name: include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
    - name: include tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../../tests/tasks/pre.yml"
  handlers:
    - name: include handlers
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../../tests/handlers/main.yml"
